COMPILER = clang
FLAGS = --std=c99 -pedantic -pedantic-errors -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough

all:	
	$(COMPILER) $(FLAGS) parityCalculator.c -o parityCalculator.out

clean:
	rm -f *.out
